### ISSUE TITLE
Test the home page text and revise it

### ISSUE THREAD

**Issue by wbreeze** [wbreeze/socelect#57]
To go really crazy, A/B test it. But there aren't that many hits.

Informally, get some people to read it and say what they think. Ask them a couple of questions to see if they got the message.

**Comment by wbreeze** [comment]
Here's one person's rewrite. It's a lot shorter. 

> Socelect offers the opportunity to assess the most likely option that satisfies the largest number of people. The questions offer a respondent the choice of indicating additional preferences. Rather than saying “I like this one”, with Socelect, you can indicate other choices in order of their appeal to you.
> 
> The resulting computation guarantees the individual preferences are aggregated to show what is preferred over the other by the majority. The process, known as Ranked Choice Voting, is superior as it allows the second, third, etc. choices to be combined.
> 
> Before you create your own question(s), you may want to explore the samples below.

Not sure about "Ranked Choice Voting." We don't use the word "voting."

**Comment by Senecafl** [comment]
Eliminate the word "Voting" as Ranked Choice is sufficient.

**Comment by wbreeze** [comment]
Socelect enables groups to ask and determine group preferences.

It obtains group members' full ordering of alternatives from most to least preferred. It combines them to produce the group preference that satisfies the majority.

**Comment by Senecafl** [comment]
When you figure out a click methodology, I assume you will put some directions on this page.

Jo Ann Lovell
JoAnnLovell@yahoo.com
